# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET https://10.0.0.98:8181/IASDTU/rs/scada/entity?muid=1dlWlpGBUvngVbeL9p1YoQ==
Accept: */*
Cache-Control: no-cache

###

POST https://10.0.0.98:8181/IASDTU/rs/scada/tube
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Cookie: JSESSIONID=836436e69b3d1624ffbfbb3068cb

{
  "brand": "1",
  "clientId": "2",
  "status": 5
}

###

GET https://10.0.0.98:8181/IASDTU/rs/scada/tubeByBrand?brand=truba60665
Accept: */*
Cache-Control: no-cache

###

GET https://10.0.0.98:8181/IASDTU/rs/scada/fittingByBrand?brand=zdv60643
Accept: */*
Cache-Control: no-cache

###

DELETE https://10.0.0.98:8181/IASDTU/rs/scada/entity?muid=PaBxB5n7Rpqa58l1jPXB7A==
Accept: */*
Cache-Control: no-cache
Cookie: JSESSIONID=836436e69b3d1624ffbfbb3068cb

###